baseURL = "https://zhangjunfelix.github.io/SLA4pg/"
publishDir = "public"
relativeURLs = false
canonifyURLs = false

[params]
  BookSection = "*"
  BookToC = true
  BookPathBase = ""

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Main navigation

[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "Syllabus"
  pageRef = "/syllabus"
  weight = 2

[[menu.main]]
  name = "Chapter 1"
  pageRef = "/chapter1"
  weight = 3

[[menu.main]]
  name = "Chapter 2"
  pageRef = "/chapter2"
  weight = 4

[[menu.main]]
  name = "Chapter 3"
  pageRef = "/chapter3"
  weight = 5

[[menu.main]]
  name = "Chapter 4"
  pageRef = "/chapter4"
  weight = 6

[[menu.main]]
  name = "Question Set 1"
  pageRef = "/questionset1"
  weight = 7

[[menu.main]]
  name = "Chapter 7"
  pageRef = "/chapter7"
  weight = 8

[[menu.main]]
  name = "Chapter 8"
  pageRef = "/chapter8"
  weight = 9

[[menu.main]]
  name = "Chapter 10"
  pageRef = "/chapter10"
  weight = 10

[[menu.main]]
  name = "Chapter 11"
  pageRef = "/chapter11"
  weight = 11

[[menu.main]]
  name = "Chapter 12"
  pageRef = "/chapter12"
  weight = 12

[[menu.main]]
  name = "Term Research Proposal"
  pageRef = "/termproposal"
  weight = 13